### ISSUE TITLE
调用多次 Board.begin后出错

### ISSUE THREAD

**Issue by huangxuangood** [DFRobot/pinpong-docs#3]
from pinpong.board import Board
import pinpong
Board("uno").begin()
print("11")
Board("uno").begin()
print("22")
RuntimeError: Invalid Arduino ID reply length

**Comment by liliang9693** [comment]
一个串口只能begin一次，如果要使用多快板子要传具体串口号的方式
`from pinpong.board import Board

boardA=Board("uno","COM1").begin()
print("11")
boardB=Board("uno","COM2").begin()
print("22")`
