### ISSUE TITLE
Having a "Read the doc" in English

### ISSUE THREAD

**Issue by mchobby** [DFRobot/pinpong-docs#7]
Hi,
Does it exists an English version of the pinpong documentation ?
Having a readme_ENG.md would also be nice.

Cheers,
Dominique
(UniHiker user)

**Comment by liliang9693** [comment]
The English document can be viewed at this link: [https://wiki.dfrobot.com/pinpong_introduction](https://wiki.dfrobot.com/pinpong_introduction)
